version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-type: "all"
        update-types:
          - "version-update:semver-major"

  # /packages ディレクトリ内の npm パッケージの依存関係をチェック
  - package-ecosystem: "npm"
    directory: "/packages/nextjs"
    schedule:
      interval: "daily"
    ignore:
      - update-types:
          - "version-update:semver-major"