version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "development"
      - update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"

  # /packages ディレクトリ内の npm パッケージの依存関係をチェック
  - package-ecosystem: "npm"
    directory: "/packages/nextjs"
    schedule:
      interval: "daily"
    allow:
      - update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
